// <auto-generated />
using System;
using Blazor_Blog.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Blazor_Blog.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20200323210602_NewData")]
    partial class NewData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Blazor_Blog.Data.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Active = true,
                            CreatedAt = new DateTime(2020, 3, 25, 16, 6, 2, 513, DateTimeKind.Local).AddTicks(4766),
                            FirstName = "john1",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 2,
                            Active = true,
                            CreatedAt = new DateTime(2020, 3, 27, 16, 6, 2, 514, DateTimeKind.Local).AddTicks(3410),
                            FirstName = "john2",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 3,
                            Active = true,
                            CreatedAt = new DateTime(2020, 3, 29, 16, 6, 2, 514, DateTimeKind.Local).AddTicks(3446),
                            FirstName = "john3",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 4,
                            Active = true,
                            CreatedAt = new DateTime(2020, 3, 31, 16, 6, 2, 514, DateTimeKind.Local).AddTicks(3452),
                            FirstName = "john4",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 5,
                            Active = true,
                            CreatedAt = new DateTime(2020, 4, 2, 16, 6, 2, 514, DateTimeKind.Local).AddTicks(3455),
                            FirstName = "john5",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 6,
                            Active = true,
                            CreatedAt = new DateTime(2020, 4, 4, 16, 6, 2, 514, DateTimeKind.Local).AddTicks(3461),
                            FirstName = "john6",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 7,
                            Active = true,
                            CreatedAt = new DateTime(2020, 4, 6, 16, 6, 2, 514, DateTimeKind.Local).AddTicks(3464),
                            FirstName = "john7",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 8,
                            Active = true,
                            CreatedAt = new DateTime(2020, 4, 8, 16, 6, 2, 514, DateTimeKind.Local).AddTicks(3467),
                            FirstName = "john8",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 9,
                            Active = true,
                            CreatedAt = new DateTime(2020, 4, 10, 16, 6, 2, 514, DateTimeKind.Local).AddTicks(3470),
                            FirstName = "john9",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 10,
                            Active = true,
                            CreatedAt = new DateTime(2020, 4, 12, 16, 6, 2, 514, DateTimeKind.Local).AddTicks(3516),
                            FirstName = "john10",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 11,
                            Active = true,
                            CreatedAt = new DateTime(2020, 4, 14, 16, 6, 2, 514, DateTimeKind.Local).AddTicks(3519),
                            FirstName = "john11",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 12,
                            Active = true,
                            CreatedAt = new DateTime(2020, 4, 16, 16, 6, 2, 514, DateTimeKind.Local).AddTicks(3522),
                            FirstName = "john12",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 13,
                            Active = true,
                            CreatedAt = new DateTime(2020, 4, 18, 16, 6, 2, 514, DateTimeKind.Local).AddTicks(3528),
                            FirstName = "john13",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 14,
                            Active = true,
                            CreatedAt = new DateTime(2020, 4, 20, 16, 6, 2, 514, DateTimeKind.Local).AddTicks(3531),
                            FirstName = "john14",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 15,
                            Active = true,
                            CreatedAt = new DateTime(2020, 4, 22, 16, 6, 2, 514, DateTimeKind.Local).AddTicks(3534),
                            FirstName = "john15",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 16,
                            Active = true,
                            CreatedAt = new DateTime(2020, 4, 24, 16, 6, 2, 514, DateTimeKind.Local).AddTicks(3537),
                            FirstName = "john16",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 17,
                            Active = true,
                            CreatedAt = new DateTime(2020, 4, 26, 16, 6, 2, 514, DateTimeKind.Local).AddTicks(3543),
                            FirstName = "john17",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 18,
                            Active = true,
                            CreatedAt = new DateTime(2020, 4, 28, 16, 6, 2, 514, DateTimeKind.Local).AddTicks(3549),
                            FirstName = "john18",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 19,
                            Active = true,
                            CreatedAt = new DateTime(2020, 4, 30, 16, 6, 2, 514, DateTimeKind.Local).AddTicks(3552),
                            FirstName = "john19",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 20,
                            Active = true,
                            CreatedAt = new DateTime(2020, 5, 2, 16, 6, 2, 514, DateTimeKind.Local).AddTicks(3555),
                            FirstName = "john20",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 21,
                            Active = true,
                            CreatedAt = new DateTime(2020, 5, 4, 16, 6, 2, 514, DateTimeKind.Local).AddTicks(3558),
                            FirstName = "john21",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 22,
                            Active = true,
                            CreatedAt = new DateTime(2020, 5, 6, 16, 6, 2, 514, DateTimeKind.Local).AddTicks(3561),
                            FirstName = "john22",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 23,
                            Active = true,
                            CreatedAt = new DateTime(2020, 5, 8, 16, 6, 2, 514, DateTimeKind.Local).AddTicks(3564),
                            FirstName = "john23",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 24,
                            Active = true,
                            CreatedAt = new DateTime(2020, 5, 10, 16, 6, 2, 514, DateTimeKind.Local).AddTicks(3570),
                            FirstName = "john24",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 25,
                            Active = true,
                            CreatedAt = new DateTime(2020, 5, 12, 16, 6, 2, 514, DateTimeKind.Local).AddTicks(3573),
                            FirstName = "john25",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 26,
                            Active = true,
                            CreatedAt = new DateTime(2020, 5, 14, 16, 6, 2, 514, DateTimeKind.Local).AddTicks(3576),
                            FirstName = "john26",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 27,
                            Active = true,
                            CreatedAt = new DateTime(2020, 5, 16, 16, 6, 2, 514, DateTimeKind.Local).AddTicks(3579),
                            FirstName = "john27",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 28,
                            Active = true,
                            CreatedAt = new DateTime(2020, 5, 18, 16, 6, 2, 514, DateTimeKind.Local).AddTicks(3582),
                            FirstName = "john28",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 29,
                            Active = true,
                            CreatedAt = new DateTime(2020, 5, 20, 16, 6, 2, 514, DateTimeKind.Local).AddTicks(3585),
                            FirstName = "john29",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 30,
                            Active = true,
                            CreatedAt = new DateTime(2020, 5, 22, 16, 6, 2, 514, DateTimeKind.Local).AddTicks(3591),
                            FirstName = "john30",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 31,
                            Active = true,
                            CreatedAt = new DateTime(2020, 5, 24, 16, 6, 2, 514, DateTimeKind.Local).AddTicks(3594),
                            FirstName = "john31",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 32,
                            Active = true,
                            CreatedAt = new DateTime(2020, 5, 26, 16, 6, 2, 514, DateTimeKind.Local).AddTicks(3597),
                            FirstName = "john32",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 33,
                            Active = true,
                            CreatedAt = new DateTime(2020, 5, 28, 16, 6, 2, 514, DateTimeKind.Local).AddTicks(3600),
                            FirstName = "john33",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 34,
                            Active = true,
                            CreatedAt = new DateTime(2020, 5, 30, 16, 6, 2, 514, DateTimeKind.Local).AddTicks(3606),
                            FirstName = "john34",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 35,
                            Active = true,
                            CreatedAt = new DateTime(2020, 6, 1, 16, 6, 2, 514, DateTimeKind.Local).AddTicks(3609),
                            FirstName = "john35",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 36,
                            Active = true,
                            CreatedAt = new DateTime(2020, 6, 3, 16, 6, 2, 514, DateTimeKind.Local).AddTicks(3612),
                            FirstName = "john36",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 37,
                            Active = true,
                            CreatedAt = new DateTime(2020, 6, 5, 16, 6, 2, 514, DateTimeKind.Local).AddTicks(3615),
                            FirstName = "john37",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 38,
                            Active = true,
                            CreatedAt = new DateTime(2020, 6, 7, 16, 6, 2, 514, DateTimeKind.Local).AddTicks(3618),
                            FirstName = "john38",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 39,
                            Active = true,
                            CreatedAt = new DateTime(2020, 6, 9, 16, 6, 2, 514, DateTimeKind.Local).AddTicks(3621),
                            FirstName = "john39",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 40,
                            Active = true,
                            CreatedAt = new DateTime(2020, 6, 11, 16, 6, 2, 514, DateTimeKind.Local).AddTicks(3627),
                            FirstName = "john40",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 41,
                            Active = true,
                            CreatedAt = new DateTime(2020, 6, 13, 16, 6, 2, 514, DateTimeKind.Local).AddTicks(3630),
                            FirstName = "john41",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 42,
                            Active = true,
                            CreatedAt = new DateTime(2020, 6, 15, 16, 6, 2, 514, DateTimeKind.Local).AddTicks(3633),
                            FirstName = "john42",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 43,
                            Active = true,
                            CreatedAt = new DateTime(2020, 6, 17, 16, 6, 2, 514, DateTimeKind.Local).AddTicks(3636),
                            FirstName = "john43",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 44,
                            Active = true,
                            CreatedAt = new DateTime(2020, 6, 19, 16, 6, 2, 514, DateTimeKind.Local).AddTicks(3639),
                            FirstName = "john44",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 45,
                            Active = true,
                            CreatedAt = new DateTime(2020, 6, 21, 16, 6, 2, 514, DateTimeKind.Local).AddTicks(3642),
                            FirstName = "john45",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 46,
                            Active = true,
                            CreatedAt = new DateTime(2020, 6, 23, 16, 6, 2, 514, DateTimeKind.Local).AddTicks(3645),
                            FirstName = "john46",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 47,
                            Active = true,
                            CreatedAt = new DateTime(2020, 6, 25, 16, 6, 2, 514, DateTimeKind.Local).AddTicks(3651),
                            FirstName = "john47",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 48,
                            Active = true,
                            CreatedAt = new DateTime(2020, 6, 27, 16, 6, 2, 514, DateTimeKind.Local).AddTicks(3678),
                            FirstName = "john48",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 49,
                            Active = true,
                            CreatedAt = new DateTime(2020, 6, 29, 16, 6, 2, 514, DateTimeKind.Local).AddTicks(3681),
                            FirstName = "john49",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 50,
                            Active = true,
                            CreatedAt = new DateTime(2020, 7, 1, 16, 6, 2, 514, DateTimeKind.Local).AddTicks(3684),
                            FirstName = "john50",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 51,
                            Active = true,
                            CreatedAt = new DateTime(2020, 7, 3, 16, 6, 2, 514, DateTimeKind.Local).AddTicks(3691),
                            FirstName = "john51",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 52,
                            Active = true,
                            CreatedAt = new DateTime(2020, 7, 5, 16, 6, 2, 514, DateTimeKind.Local).AddTicks(3694),
                            FirstName = "john52",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 53,
                            Active = true,
                            CreatedAt = new DateTime(2020, 7, 7, 16, 6, 2, 514, DateTimeKind.Local).AddTicks(3697),
                            FirstName = "john53",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 54,
                            Active = true,
                            CreatedAt = new DateTime(2020, 7, 9, 16, 6, 2, 514, DateTimeKind.Local).AddTicks(3700),
                            FirstName = "john54",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 55,
                            Active = true,
                            CreatedAt = new DateTime(2020, 7, 11, 16, 6, 2, 514, DateTimeKind.Local).AddTicks(3706),
                            FirstName = "john55",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 56,
                            Active = true,
                            CreatedAt = new DateTime(2020, 7, 13, 16, 6, 2, 514, DateTimeKind.Local).AddTicks(3709),
                            FirstName = "john56",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 57,
                            Active = true,
                            CreatedAt = new DateTime(2020, 7, 15, 16, 6, 2, 514, DateTimeKind.Local).AddTicks(3712),
                            FirstName = "john57",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 58,
                            Active = true,
                            CreatedAt = new DateTime(2020, 7, 17, 16, 6, 2, 514, DateTimeKind.Local).AddTicks(3715),
                            FirstName = "john58",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 59,
                            Active = true,
                            CreatedAt = new DateTime(2020, 7, 19, 16, 6, 2, 514, DateTimeKind.Local).AddTicks(3718),
                            FirstName = "john59",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 60,
                            Active = true,
                            CreatedAt = new DateTime(2020, 7, 21, 16, 6, 2, 514, DateTimeKind.Local).AddTicks(3724),
                            FirstName = "john60",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 61,
                            Active = true,
                            CreatedAt = new DateTime(2020, 7, 23, 16, 6, 2, 514, DateTimeKind.Local).AddTicks(3727),
                            FirstName = "john61",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 62,
                            Active = true,
                            CreatedAt = new DateTime(2020, 7, 25, 16, 6, 2, 514, DateTimeKind.Local).AddTicks(3730),
                            FirstName = "john62",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 63,
                            Active = true,
                            CreatedAt = new DateTime(2020, 7, 27, 16, 6, 2, 514, DateTimeKind.Local).AddTicks(3733),
                            FirstName = "john63",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 64,
                            Active = true,
                            CreatedAt = new DateTime(2020, 7, 29, 16, 6, 2, 514, DateTimeKind.Local).AddTicks(3739),
                            FirstName = "john64",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 65,
                            Active = true,
                            CreatedAt = new DateTime(2020, 7, 31, 16, 6, 2, 514, DateTimeKind.Local).AddTicks(3742),
                            FirstName = "john65",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 66,
                            Active = true,
                            CreatedAt = new DateTime(2020, 8, 2, 16, 6, 2, 514, DateTimeKind.Local).AddTicks(3748),
                            FirstName = "john66",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 67,
                            Active = true,
                            CreatedAt = new DateTime(2020, 8, 4, 16, 6, 2, 514, DateTimeKind.Local).AddTicks(3751),
                            FirstName = "john67",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 68,
                            Active = true,
                            CreatedAt = new DateTime(2020, 8, 6, 16, 6, 2, 514, DateTimeKind.Local).AddTicks(3754),
                            FirstName = "john68",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 69,
                            Active = true,
                            CreatedAt = new DateTime(2020, 8, 8, 16, 6, 2, 514, DateTimeKind.Local).AddTicks(3757),
                            FirstName = "john69",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 70,
                            Active = true,
                            CreatedAt = new DateTime(2020, 8, 10, 16, 6, 2, 514, DateTimeKind.Local).AddTicks(3763),
                            FirstName = "john70",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 71,
                            Active = true,
                            CreatedAt = new DateTime(2020, 8, 12, 16, 6, 2, 514, DateTimeKind.Local).AddTicks(3766),
                            FirstName = "john71",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 72,
                            Active = true,
                            CreatedAt = new DateTime(2020, 8, 14, 16, 6, 2, 514, DateTimeKind.Local).AddTicks(3769),
                            FirstName = "john72",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 73,
                            Active = true,
                            CreatedAt = new DateTime(2020, 8, 16, 16, 6, 2, 514, DateTimeKind.Local).AddTicks(3772),
                            FirstName = "john73",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 74,
                            Active = true,
                            CreatedAt = new DateTime(2020, 8, 18, 16, 6, 2, 514, DateTimeKind.Local).AddTicks(3778),
                            FirstName = "john74",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 75,
                            Active = true,
                            CreatedAt = new DateTime(2020, 8, 20, 16, 6, 2, 514, DateTimeKind.Local).AddTicks(3781),
                            FirstName = "john75",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 76,
                            Active = true,
                            CreatedAt = new DateTime(2020, 8, 22, 16, 6, 2, 514, DateTimeKind.Local).AddTicks(3784),
                            FirstName = "john76",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 77,
                            Active = true,
                            CreatedAt = new DateTime(2020, 8, 24, 16, 6, 2, 514, DateTimeKind.Local).AddTicks(3787),
                            FirstName = "john77",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 78,
                            Active = true,
                            CreatedAt = new DateTime(2020, 8, 26, 16, 6, 2, 514, DateTimeKind.Local).AddTicks(3790),
                            FirstName = "john78",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 79,
                            Active = true,
                            CreatedAt = new DateTime(2020, 8, 28, 16, 6, 2, 514, DateTimeKind.Local).AddTicks(3796),
                            FirstName = "john79",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 80,
                            Active = true,
                            CreatedAt = new DateTime(2020, 8, 30, 16, 6, 2, 514, DateTimeKind.Local).AddTicks(3799),
                            FirstName = "john80",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 81,
                            Active = true,
                            CreatedAt = new DateTime(2020, 9, 1, 16, 6, 2, 514, DateTimeKind.Local).AddTicks(3802),
                            FirstName = "john81",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 82,
                            Active = true,
                            CreatedAt = new DateTime(2020, 9, 3, 16, 6, 2, 514, DateTimeKind.Local).AddTicks(3805),
                            FirstName = "john82",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 83,
                            Active = true,
                            CreatedAt = new DateTime(2020, 9, 5, 16, 6, 2, 514, DateTimeKind.Local).AddTicks(3811),
                            FirstName = "john83",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 84,
                            Active = true,
                            CreatedAt = new DateTime(2020, 9, 7, 16, 6, 2, 514, DateTimeKind.Local).AddTicks(3814),
                            FirstName = "john84",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 85,
                            Active = true,
                            CreatedAt = new DateTime(2020, 9, 9, 16, 6, 2, 514, DateTimeKind.Local).AddTicks(3817),
                            FirstName = "john85",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 86,
                            Active = true,
                            CreatedAt = new DateTime(2020, 9, 11, 16, 6, 2, 514, DateTimeKind.Local).AddTicks(3847),
                            FirstName = "john86",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 87,
                            Active = true,
                            CreatedAt = new DateTime(2020, 9, 13, 16, 6, 2, 514, DateTimeKind.Local).AddTicks(3850),
                            FirstName = "john87",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 88,
                            Active = true,
                            CreatedAt = new DateTime(2020, 9, 15, 16, 6, 2, 514, DateTimeKind.Local).AddTicks(3853),
                            FirstName = "john88",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 89,
                            Active = true,
                            CreatedAt = new DateTime(2020, 9, 17, 16, 6, 2, 514, DateTimeKind.Local).AddTicks(3860),
                            FirstName = "john89",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 90,
                            Active = true,
                            CreatedAt = new DateTime(2020, 9, 19, 16, 6, 2, 514, DateTimeKind.Local).AddTicks(3863),
                            FirstName = "john90",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 91,
                            Active = true,
                            CreatedAt = new DateTime(2020, 9, 21, 16, 6, 2, 514, DateTimeKind.Local).AddTicks(3866),
                            FirstName = "john91",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 92,
                            Active = true,
                            CreatedAt = new DateTime(2020, 9, 23, 16, 6, 2, 514, DateTimeKind.Local).AddTicks(3869),
                            FirstName = "john92",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 93,
                            Active = true,
                            CreatedAt = new DateTime(2020, 9, 25, 16, 6, 2, 514, DateTimeKind.Local).AddTicks(3875),
                            FirstName = "john93",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 94,
                            Active = true,
                            CreatedAt = new DateTime(2020, 9, 27, 16, 6, 2, 514, DateTimeKind.Local).AddTicks(3878),
                            FirstName = "john94",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 95,
                            Active = true,
                            CreatedAt = new DateTime(2020, 9, 29, 16, 6, 2, 514, DateTimeKind.Local).AddTicks(3881),
                            FirstName = "john95",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 96,
                            Active = true,
                            CreatedAt = new DateTime(2020, 10, 1, 16, 6, 2, 514, DateTimeKind.Local).AddTicks(3884),
                            FirstName = "john96",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 97,
                            Active = true,
                            CreatedAt = new DateTime(2020, 10, 3, 16, 6, 2, 514, DateTimeKind.Local).AddTicks(3890),
                            FirstName = "john97",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 98,
                            Active = true,
                            CreatedAt = new DateTime(2020, 10, 5, 16, 6, 2, 514, DateTimeKind.Local).AddTicks(3893),
                            FirstName = "john98",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 99,
                            Active = true,
                            CreatedAt = new DateTime(2020, 10, 7, 16, 6, 2, 514, DateTimeKind.Local).AddTicks(3896),
                            FirstName = "john99",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
