// <auto-generated />
using System;
using Blazor_Blog.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Blazor_Blog.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20200320235305_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Blazor_Blog.Data.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            CreatedAt = new DateTime(2020, 3, 22, 18, 53, 5, 260, DateTimeKind.Local).AddTicks(981),
                            FirstName = "john1",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 2,
                            CreatedAt = new DateTime(2020, 3, 24, 18, 53, 5, 260, DateTimeKind.Local).AddTicks(9982),
                            FirstName = "john2",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 3,
                            CreatedAt = new DateTime(2020, 3, 26, 18, 53, 5, 261, DateTimeKind.Local).AddTicks(6),
                            FirstName = "john3",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 4,
                            CreatedAt = new DateTime(2020, 3, 28, 18, 53, 5, 261, DateTimeKind.Local).AddTicks(9),
                            FirstName = "john4",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 5,
                            CreatedAt = new DateTime(2020, 3, 30, 18, 53, 5, 261, DateTimeKind.Local).AddTicks(12),
                            FirstName = "john5",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 6,
                            CreatedAt = new DateTime(2020, 4, 1, 18, 53, 5, 261, DateTimeKind.Local).AddTicks(21),
                            FirstName = "john6",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 7,
                            CreatedAt = new DateTime(2020, 4, 3, 18, 53, 5, 261, DateTimeKind.Local).AddTicks(24),
                            FirstName = "john7",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 8,
                            CreatedAt = new DateTime(2020, 4, 5, 18, 53, 5, 261, DateTimeKind.Local).AddTicks(27),
                            FirstName = "john8",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 9,
                            CreatedAt = new DateTime(2020, 4, 7, 18, 53, 5, 261, DateTimeKind.Local).AddTicks(30),
                            FirstName = "john9",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 10,
                            CreatedAt = new DateTime(2020, 4, 9, 18, 53, 5, 261, DateTimeKind.Local).AddTicks(36),
                            FirstName = "john10",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 11,
                            CreatedAt = new DateTime(2020, 4, 11, 18, 53, 5, 261, DateTimeKind.Local).AddTicks(39),
                            FirstName = "john11",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 12,
                            CreatedAt = new DateTime(2020, 4, 13, 18, 53, 5, 261, DateTimeKind.Local).AddTicks(45),
                            FirstName = "john12",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 13,
                            CreatedAt = new DateTime(2020, 4, 15, 18, 53, 5, 261, DateTimeKind.Local).AddTicks(48),
                            FirstName = "john13",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 14,
                            CreatedAt = new DateTime(2020, 4, 17, 18, 53, 5, 261, DateTimeKind.Local).AddTicks(51),
                            FirstName = "john14",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 15,
                            CreatedAt = new DateTime(2020, 4, 19, 18, 53, 5, 261, DateTimeKind.Local).AddTicks(54),
                            FirstName = "john15",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 16,
                            CreatedAt = new DateTime(2020, 4, 21, 18, 53, 5, 261, DateTimeKind.Local).AddTicks(60),
                            FirstName = "john16",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 17,
                            CreatedAt = new DateTime(2020, 4, 23, 18, 53, 5, 261, DateTimeKind.Local).AddTicks(63),
                            FirstName = "john17",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 18,
                            CreatedAt = new DateTime(2020, 4, 25, 18, 53, 5, 261, DateTimeKind.Local).AddTicks(69),
                            FirstName = "john18",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 19,
                            CreatedAt = new DateTime(2020, 4, 27, 18, 53, 5, 261, DateTimeKind.Local).AddTicks(72),
                            FirstName = "john19",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 20,
                            CreatedAt = new DateTime(2020, 4, 29, 18, 53, 5, 261, DateTimeKind.Local).AddTicks(75),
                            FirstName = "john20",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 21,
                            CreatedAt = new DateTime(2020, 5, 1, 18, 53, 5, 261, DateTimeKind.Local).AddTicks(78),
                            FirstName = "john21",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 22,
                            CreatedAt = new DateTime(2020, 5, 3, 18, 53, 5, 261, DateTimeKind.Local).AddTicks(81),
                            FirstName = "john22",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 23,
                            CreatedAt = new DateTime(2020, 5, 5, 18, 53, 5, 261, DateTimeKind.Local).AddTicks(124),
                            FirstName = "john23",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 24,
                            CreatedAt = new DateTime(2020, 5, 7, 18, 53, 5, 261, DateTimeKind.Local).AddTicks(130),
                            FirstName = "john24",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 25,
                            CreatedAt = new DateTime(2020, 5, 9, 18, 53, 5, 261, DateTimeKind.Local).AddTicks(133),
                            FirstName = "john25",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 26,
                            CreatedAt = new DateTime(2020, 5, 11, 18, 53, 5, 261, DateTimeKind.Local).AddTicks(136),
                            FirstName = "john26",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 27,
                            CreatedAt = new DateTime(2020, 5, 13, 18, 53, 5, 261, DateTimeKind.Local).AddTicks(139),
                            FirstName = "john27",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 28,
                            CreatedAt = new DateTime(2020, 5, 15, 18, 53, 5, 261, DateTimeKind.Local).AddTicks(142),
                            FirstName = "john28",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 29,
                            CreatedAt = new DateTime(2020, 5, 17, 18, 53, 5, 261, DateTimeKind.Local).AddTicks(145),
                            FirstName = "john29",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 30,
                            CreatedAt = new DateTime(2020, 5, 19, 18, 53, 5, 261, DateTimeKind.Local).AddTicks(151),
                            FirstName = "john30",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 31,
                            CreatedAt = new DateTime(2020, 5, 21, 18, 53, 5, 261, DateTimeKind.Local).AddTicks(154),
                            FirstName = "john31",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 32,
                            CreatedAt = new DateTime(2020, 5, 23, 18, 53, 5, 261, DateTimeKind.Local).AddTicks(157),
                            FirstName = "john32",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 33,
                            CreatedAt = new DateTime(2020, 5, 25, 18, 53, 5, 261, DateTimeKind.Local).AddTicks(160),
                            FirstName = "john33",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 34,
                            CreatedAt = new DateTime(2020, 5, 27, 18, 53, 5, 261, DateTimeKind.Local).AddTicks(166),
                            FirstName = "john34",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 35,
                            CreatedAt = new DateTime(2020, 5, 29, 18, 53, 5, 261, DateTimeKind.Local).AddTicks(169),
                            FirstName = "john35",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 36,
                            CreatedAt = new DateTime(2020, 5, 31, 18, 53, 5, 261, DateTimeKind.Local).AddTicks(172),
                            FirstName = "john36",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 37,
                            CreatedAt = new DateTime(2020, 6, 2, 18, 53, 5, 261, DateTimeKind.Local).AddTicks(178),
                            FirstName = "john37",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 38,
                            CreatedAt = new DateTime(2020, 6, 4, 18, 53, 5, 261, DateTimeKind.Local).AddTicks(181),
                            FirstName = "john38",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 39,
                            CreatedAt = new DateTime(2020, 6, 6, 18, 53, 5, 261, DateTimeKind.Local).AddTicks(184),
                            FirstName = "john39",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 40,
                            CreatedAt = new DateTime(2020, 6, 8, 18, 53, 5, 261, DateTimeKind.Local).AddTicks(187),
                            FirstName = "john40",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 41,
                            CreatedAt = new DateTime(2020, 6, 10, 18, 53, 5, 261, DateTimeKind.Local).AddTicks(190),
                            FirstName = "john41",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 42,
                            CreatedAt = new DateTime(2020, 6, 12, 18, 53, 5, 261, DateTimeKind.Local).AddTicks(196),
                            FirstName = "john42",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 43,
                            CreatedAt = new DateTime(2020, 6, 14, 18, 53, 5, 261, DateTimeKind.Local).AddTicks(199),
                            FirstName = "john43",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 44,
                            CreatedAt = new DateTime(2020, 6, 16, 18, 53, 5, 261, DateTimeKind.Local).AddTicks(202),
                            FirstName = "john44",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 45,
                            CreatedAt = new DateTime(2020, 6, 18, 18, 53, 5, 261, DateTimeKind.Local).AddTicks(205),
                            FirstName = "john45",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 46,
                            CreatedAt = new DateTime(2020, 6, 20, 18, 53, 5, 261, DateTimeKind.Local).AddTicks(208),
                            FirstName = "john46",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 47,
                            CreatedAt = new DateTime(2020, 6, 22, 18, 53, 5, 261, DateTimeKind.Local).AddTicks(214),
                            FirstName = "john47",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 48,
                            CreatedAt = new DateTime(2020, 6, 24, 18, 53, 5, 261, DateTimeKind.Local).AddTicks(217),
                            FirstName = "john48",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 49,
                            CreatedAt = new DateTime(2020, 6, 26, 18, 53, 5, 261, DateTimeKind.Local).AddTicks(220),
                            FirstName = "john49",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 50,
                            CreatedAt = new DateTime(2020, 6, 28, 18, 53, 5, 261, DateTimeKind.Local).AddTicks(223),
                            FirstName = "john50",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 51,
                            CreatedAt = new DateTime(2020, 6, 30, 18, 53, 5, 261, DateTimeKind.Local).AddTicks(226),
                            FirstName = "john51",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 52,
                            CreatedAt = new DateTime(2020, 7, 2, 18, 53, 5, 261, DateTimeKind.Local).AddTicks(229),
                            FirstName = "john52",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 53,
                            CreatedAt = new DateTime(2020, 7, 4, 18, 53, 5, 261, DateTimeKind.Local).AddTicks(235),
                            FirstName = "john53",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 54,
                            CreatedAt = new DateTime(2020, 7, 6, 18, 53, 5, 261, DateTimeKind.Local).AddTicks(238),
                            FirstName = "john54",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 55,
                            CreatedAt = new DateTime(2020, 7, 8, 18, 53, 5, 261, DateTimeKind.Local).AddTicks(241),
                            FirstName = "john55",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 56,
                            CreatedAt = new DateTime(2020, 7, 10, 18, 53, 5, 261, DateTimeKind.Local).AddTicks(244),
                            FirstName = "john56",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 57,
                            CreatedAt = new DateTime(2020, 7, 12, 18, 53, 5, 261, DateTimeKind.Local).AddTicks(247),
                            FirstName = "john57",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 58,
                            CreatedAt = new DateTime(2020, 7, 14, 18, 53, 5, 261, DateTimeKind.Local).AddTicks(253),
                            FirstName = "john58",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 59,
                            CreatedAt = new DateTime(2020, 7, 16, 18, 53, 5, 261, DateTimeKind.Local).AddTicks(256),
                            FirstName = "john59",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 60,
                            CreatedAt = new DateTime(2020, 7, 18, 18, 53, 5, 261, DateTimeKind.Local).AddTicks(259),
                            FirstName = "john60",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 61,
                            CreatedAt = new DateTime(2020, 7, 20, 18, 53, 5, 261, DateTimeKind.Local).AddTicks(262),
                            FirstName = "john61",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 62,
                            CreatedAt = new DateTime(2020, 7, 22, 18, 53, 5, 261, DateTimeKind.Local).AddTicks(265),
                            FirstName = "john62",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 63,
                            CreatedAt = new DateTime(2020, 7, 24, 18, 53, 5, 261, DateTimeKind.Local).AddTicks(296),
                            FirstName = "john63",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 64,
                            CreatedAt = new DateTime(2020, 7, 26, 18, 53, 5, 261, DateTimeKind.Local).AddTicks(299),
                            FirstName = "john64",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 65,
                            CreatedAt = new DateTime(2020, 7, 28, 18, 53, 5, 261, DateTimeKind.Local).AddTicks(305),
                            FirstName = "john65",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 66,
                            CreatedAt = new DateTime(2020, 7, 30, 18, 53, 5, 261, DateTimeKind.Local).AddTicks(311),
                            FirstName = "john66",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 67,
                            CreatedAt = new DateTime(2020, 8, 1, 18, 53, 5, 261, DateTimeKind.Local).AddTicks(314),
                            FirstName = "john67",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 68,
                            CreatedAt = new DateTime(2020, 8, 3, 18, 53, 5, 261, DateTimeKind.Local).AddTicks(317),
                            FirstName = "john68",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 69,
                            CreatedAt = new DateTime(2020, 8, 5, 18, 53, 5, 261, DateTimeKind.Local).AddTicks(320),
                            FirstName = "john69",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 70,
                            CreatedAt = new DateTime(2020, 8, 7, 18, 53, 5, 261, DateTimeKind.Local).AddTicks(323),
                            FirstName = "john70",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 71,
                            CreatedAt = new DateTime(2020, 8, 9, 18, 53, 5, 261, DateTimeKind.Local).AddTicks(329),
                            FirstName = "john71",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 72,
                            CreatedAt = new DateTime(2020, 8, 11, 18, 53, 5, 261, DateTimeKind.Local).AddTicks(332),
                            FirstName = "john72",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 73,
                            CreatedAt = new DateTime(2020, 8, 13, 18, 53, 5, 261, DateTimeKind.Local).AddTicks(335),
                            FirstName = "john73",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 74,
                            CreatedAt = new DateTime(2020, 8, 15, 18, 53, 5, 261, DateTimeKind.Local).AddTicks(338),
                            FirstName = "john74",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 75,
                            CreatedAt = new DateTime(2020, 8, 17, 18, 53, 5, 261, DateTimeKind.Local).AddTicks(341),
                            FirstName = "john75",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 76,
                            CreatedAt = new DateTime(2020, 8, 19, 18, 53, 5, 261, DateTimeKind.Local).AddTicks(344),
                            FirstName = "john76",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 77,
                            CreatedAt = new DateTime(2020, 8, 21, 18, 53, 5, 261, DateTimeKind.Local).AddTicks(350),
                            FirstName = "john77",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 78,
                            CreatedAt = new DateTime(2020, 8, 23, 18, 53, 5, 261, DateTimeKind.Local).AddTicks(353),
                            FirstName = "john78",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 79,
                            CreatedAt = new DateTime(2020, 8, 25, 18, 53, 5, 261, DateTimeKind.Local).AddTicks(356),
                            FirstName = "john79",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 80,
                            CreatedAt = new DateTime(2020, 8, 27, 18, 53, 5, 261, DateTimeKind.Local).AddTicks(359),
                            FirstName = "john80",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 81,
                            CreatedAt = new DateTime(2020, 8, 29, 18, 53, 5, 261, DateTimeKind.Local).AddTicks(362),
                            FirstName = "john81",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 82,
                            CreatedAt = new DateTime(2020, 8, 31, 18, 53, 5, 261, DateTimeKind.Local).AddTicks(368),
                            FirstName = "john82",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 83,
                            CreatedAt = new DateTime(2020, 9, 2, 18, 53, 5, 261, DateTimeKind.Local).AddTicks(371),
                            FirstName = "john83",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 84,
                            CreatedAt = new DateTime(2020, 9, 4, 18, 53, 5, 261, DateTimeKind.Local).AddTicks(374),
                            FirstName = "john84",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 85,
                            CreatedAt = new DateTime(2020, 9, 6, 18, 53, 5, 261, DateTimeKind.Local).AddTicks(377),
                            FirstName = "john85",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 86,
                            CreatedAt = new DateTime(2020, 9, 8, 18, 53, 5, 261, DateTimeKind.Local).AddTicks(380),
                            FirstName = "john86",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 87,
                            CreatedAt = new DateTime(2020, 9, 10, 18, 53, 5, 261, DateTimeKind.Local).AddTicks(386),
                            FirstName = "john87",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 88,
                            CreatedAt = new DateTime(2020, 9, 12, 18, 53, 5, 261, DateTimeKind.Local).AddTicks(389),
                            FirstName = "john88",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 89,
                            CreatedAt = new DateTime(2020, 9, 14, 18, 53, 5, 261, DateTimeKind.Local).AddTicks(392),
                            FirstName = "john89",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 90,
                            CreatedAt = new DateTime(2020, 9, 16, 18, 53, 5, 261, DateTimeKind.Local).AddTicks(395),
                            FirstName = "john90",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 91,
                            CreatedAt = new DateTime(2020, 9, 18, 18, 53, 5, 261, DateTimeKind.Local).AddTicks(398),
                            FirstName = "john91",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 92,
                            CreatedAt = new DateTime(2020, 9, 20, 18, 53, 5, 261, DateTimeKind.Local).AddTicks(404),
                            FirstName = "john92",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 93,
                            CreatedAt = new DateTime(2020, 9, 22, 18, 53, 5, 261, DateTimeKind.Local).AddTicks(407),
                            FirstName = "john93",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 94,
                            CreatedAt = new DateTime(2020, 9, 24, 18, 53, 5, 261, DateTimeKind.Local).AddTicks(410),
                            FirstName = "john94",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 95,
                            CreatedAt = new DateTime(2020, 9, 26, 18, 53, 5, 261, DateTimeKind.Local).AddTicks(413),
                            FirstName = "john95",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 96,
                            CreatedAt = new DateTime(2020, 9, 28, 18, 53, 5, 261, DateTimeKind.Local).AddTicks(416),
                            FirstName = "john96",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 97,
                            CreatedAt = new DateTime(2020, 9, 30, 18, 53, 5, 261, DateTimeKind.Local).AddTicks(422),
                            FirstName = "john97",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 98,
                            CreatedAt = new DateTime(2020, 10, 2, 18, 53, 5, 261, DateTimeKind.Local).AddTicks(425),
                            FirstName = "john98",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 99,
                            CreatedAt = new DateTime(2020, 10, 4, 18, 53, 5, 261, DateTimeKind.Local).AddTicks(428),
                            FirstName = "john99",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
