// <auto-generated />
using System;
using Blazor_Blog.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Blazor_Blog.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20200323203349_updated")]
    partial class updated
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Blazor_Blog.Data.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Active = false,
                            CreatedAt = new DateTime(2020, 3, 25, 15, 33, 48, 607, DateTimeKind.Local).AddTicks(4196),
                            FirstName = "john1",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 2,
                            Active = false,
                            CreatedAt = new DateTime(2020, 3, 27, 15, 33, 48, 608, DateTimeKind.Local).AddTicks(2699),
                            FirstName = "john2",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 3,
                            Active = false,
                            CreatedAt = new DateTime(2020, 3, 29, 15, 33, 48, 608, DateTimeKind.Local).AddTicks(2723),
                            FirstName = "john3",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 4,
                            Active = false,
                            CreatedAt = new DateTime(2020, 3, 31, 15, 33, 48, 608, DateTimeKind.Local).AddTicks(2729),
                            FirstName = "john4",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 5,
                            Active = false,
                            CreatedAt = new DateTime(2020, 4, 2, 15, 33, 48, 608, DateTimeKind.Local).AddTicks(2732),
                            FirstName = "john5",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 6,
                            Active = false,
                            CreatedAt = new DateTime(2020, 4, 4, 15, 33, 48, 608, DateTimeKind.Local).AddTicks(2738),
                            FirstName = "john6",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 7,
                            Active = false,
                            CreatedAt = new DateTime(2020, 4, 6, 15, 33, 48, 608, DateTimeKind.Local).AddTicks(2741),
                            FirstName = "john7",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 8,
                            Active = false,
                            CreatedAt = new DateTime(2020, 4, 8, 15, 33, 48, 608, DateTimeKind.Local).AddTicks(2747),
                            FirstName = "john8",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 9,
                            Active = false,
                            CreatedAt = new DateTime(2020, 4, 10, 15, 33, 48, 608, DateTimeKind.Local).AddTicks(2750),
                            FirstName = "john9",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 10,
                            Active = false,
                            CreatedAt = new DateTime(2020, 4, 12, 15, 33, 48, 608, DateTimeKind.Local).AddTicks(2756),
                            FirstName = "john10",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 11,
                            Active = false,
                            CreatedAt = new DateTime(2020, 4, 14, 15, 33, 48, 608, DateTimeKind.Local).AddTicks(2759),
                            FirstName = "john11",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 12,
                            Active = false,
                            CreatedAt = new DateTime(2020, 4, 16, 15, 33, 48, 608, DateTimeKind.Local).AddTicks(2762),
                            FirstName = "john12",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 13,
                            Active = false,
                            CreatedAt = new DateTime(2020, 4, 18, 15, 33, 48, 608, DateTimeKind.Local).AddTicks(2768),
                            FirstName = "john13",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 14,
                            Active = false,
                            CreatedAt = new DateTime(2020, 4, 20, 15, 33, 48, 608, DateTimeKind.Local).AddTicks(2771),
                            FirstName = "john14",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 15,
                            Active = false,
                            CreatedAt = new DateTime(2020, 4, 22, 15, 33, 48, 608, DateTimeKind.Local).AddTicks(2774),
                            FirstName = "john15",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 16,
                            Active = false,
                            CreatedAt = new DateTime(2020, 4, 24, 15, 33, 48, 608, DateTimeKind.Local).AddTicks(2777),
                            FirstName = "john16",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 17,
                            Active = false,
                            CreatedAt = new DateTime(2020, 4, 26, 15, 33, 48, 608, DateTimeKind.Local).AddTicks(2783),
                            FirstName = "john17",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 18,
                            Active = false,
                            CreatedAt = new DateTime(2020, 4, 28, 15, 33, 48, 608, DateTimeKind.Local).AddTicks(2786),
                            FirstName = "john18",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 19,
                            Active = false,
                            CreatedAt = new DateTime(2020, 4, 30, 15, 33, 48, 608, DateTimeKind.Local).AddTicks(2792),
                            FirstName = "john19",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 20,
                            Active = false,
                            CreatedAt = new DateTime(2020, 5, 2, 15, 33, 48, 608, DateTimeKind.Local).AddTicks(2795),
                            FirstName = "john20",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 21,
                            Active = false,
                            CreatedAt = new DateTime(2020, 5, 4, 15, 33, 48, 608, DateTimeKind.Local).AddTicks(2798),
                            FirstName = "john21",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 22,
                            Active = false,
                            CreatedAt = new DateTime(2020, 5, 6, 15, 33, 48, 608, DateTimeKind.Local).AddTicks(2801),
                            FirstName = "john22",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 23,
                            Active = false,
                            CreatedAt = new DateTime(2020, 5, 8, 15, 33, 48, 608, DateTimeKind.Local).AddTicks(2804),
                            FirstName = "john23",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 24,
                            Active = false,
                            CreatedAt = new DateTime(2020, 5, 10, 15, 33, 48, 608, DateTimeKind.Local).AddTicks(2810),
                            FirstName = "john24",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 25,
                            Active = false,
                            CreatedAt = new DateTime(2020, 5, 12, 15, 33, 48, 608, DateTimeKind.Local).AddTicks(2813),
                            FirstName = "john25",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 26,
                            Active = false,
                            CreatedAt = new DateTime(2020, 5, 14, 15, 33, 48, 608, DateTimeKind.Local).AddTicks(2816),
                            FirstName = "john26",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 27,
                            Active = false,
                            CreatedAt = new DateTime(2020, 5, 16, 15, 33, 48, 608, DateTimeKind.Local).AddTicks(2819),
                            FirstName = "john27",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 28,
                            Active = false,
                            CreatedAt = new DateTime(2020, 5, 18, 15, 33, 48, 608, DateTimeKind.Local).AddTicks(2822),
                            FirstName = "john28",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 29,
                            Active = false,
                            CreatedAt = new DateTime(2020, 5, 20, 15, 33, 48, 608, DateTimeKind.Local).AddTicks(2828),
                            FirstName = "john29",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 30,
                            Active = false,
                            CreatedAt = new DateTime(2020, 5, 22, 15, 33, 48, 608, DateTimeKind.Local).AddTicks(2831),
                            FirstName = "john30",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 31,
                            Active = false,
                            CreatedAt = new DateTime(2020, 5, 24, 15, 33, 48, 608, DateTimeKind.Local).AddTicks(2925),
                            FirstName = "john31",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 32,
                            Active = false,
                            CreatedAt = new DateTime(2020, 5, 26, 15, 33, 48, 608, DateTimeKind.Local).AddTicks(2928),
                            FirstName = "john32",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 33,
                            Active = false,
                            CreatedAt = new DateTime(2020, 5, 28, 15, 33, 48, 608, DateTimeKind.Local).AddTicks(2934),
                            FirstName = "john33",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 34,
                            Active = false,
                            CreatedAt = new DateTime(2020, 5, 30, 15, 33, 48, 608, DateTimeKind.Local).AddTicks(2937),
                            FirstName = "john34",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 35,
                            Active = false,
                            CreatedAt = new DateTime(2020, 6, 1, 15, 33, 48, 608, DateTimeKind.Local).AddTicks(2943),
                            FirstName = "john35",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 36,
                            Active = false,
                            CreatedAt = new DateTime(2020, 6, 3, 15, 33, 48, 608, DateTimeKind.Local).AddTicks(2946),
                            FirstName = "john36",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 37,
                            Active = false,
                            CreatedAt = new DateTime(2020, 6, 5, 15, 33, 48, 608, DateTimeKind.Local).AddTicks(2949),
                            FirstName = "john37",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 38,
                            Active = false,
                            CreatedAt = new DateTime(2020, 6, 7, 15, 33, 48, 608, DateTimeKind.Local).AddTicks(2952),
                            FirstName = "john38",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 39,
                            Active = false,
                            CreatedAt = new DateTime(2020, 6, 9, 15, 33, 48, 608, DateTimeKind.Local).AddTicks(2955),
                            FirstName = "john39",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 40,
                            Active = false,
                            CreatedAt = new DateTime(2020, 6, 11, 15, 33, 48, 608, DateTimeKind.Local).AddTicks(2961),
                            FirstName = "john40",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 41,
                            Active = false,
                            CreatedAt = new DateTime(2020, 6, 13, 15, 33, 48, 608, DateTimeKind.Local).AddTicks(2964),
                            FirstName = "john41",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 42,
                            Active = false,
                            CreatedAt = new DateTime(2020, 6, 15, 15, 33, 48, 608, DateTimeKind.Local).AddTicks(2967),
                            FirstName = "john42",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 43,
                            Active = false,
                            CreatedAt = new DateTime(2020, 6, 17, 15, 33, 48, 608, DateTimeKind.Local).AddTicks(2970),
                            FirstName = "john43",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 44,
                            Active = false,
                            CreatedAt = new DateTime(2020, 6, 19, 15, 33, 48, 608, DateTimeKind.Local).AddTicks(2973),
                            FirstName = "john44",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 45,
                            Active = false,
                            CreatedAt = new DateTime(2020, 6, 21, 15, 33, 48, 608, DateTimeKind.Local).AddTicks(2979),
                            FirstName = "john45",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 46,
                            Active = false,
                            CreatedAt = new DateTime(2020, 6, 23, 15, 33, 48, 608, DateTimeKind.Local).AddTicks(2982),
                            FirstName = "john46",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 47,
                            Active = false,
                            CreatedAt = new DateTime(2020, 6, 25, 15, 33, 48, 608, DateTimeKind.Local).AddTicks(2985),
                            FirstName = "john47",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 48,
                            Active = false,
                            CreatedAt = new DateTime(2020, 6, 27, 15, 33, 48, 608, DateTimeKind.Local).AddTicks(2988),
                            FirstName = "john48",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 49,
                            Active = false,
                            CreatedAt = new DateTime(2020, 6, 29, 15, 33, 48, 608, DateTimeKind.Local).AddTicks(2991),
                            FirstName = "john49",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 50,
                            Active = false,
                            CreatedAt = new DateTime(2020, 7, 1, 15, 33, 48, 608, DateTimeKind.Local).AddTicks(2997),
                            FirstName = "john50",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 51,
                            Active = false,
                            CreatedAt = new DateTime(2020, 7, 3, 15, 33, 48, 608, DateTimeKind.Local).AddTicks(3000),
                            FirstName = "john51",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 52,
                            Active = false,
                            CreatedAt = new DateTime(2020, 7, 5, 15, 33, 48, 608, DateTimeKind.Local).AddTicks(3003),
                            FirstName = "john52",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 53,
                            Active = false,
                            CreatedAt = new DateTime(2020, 7, 7, 15, 33, 48, 608, DateTimeKind.Local).AddTicks(3006),
                            FirstName = "john53",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 54,
                            Active = false,
                            CreatedAt = new DateTime(2020, 7, 9, 15, 33, 48, 608, DateTimeKind.Local).AddTicks(3009),
                            FirstName = "john54",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 55,
                            Active = false,
                            CreatedAt = new DateTime(2020, 7, 11, 15, 33, 48, 608, DateTimeKind.Local).AddTicks(3015),
                            FirstName = "john55",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 56,
                            Active = false,
                            CreatedAt = new DateTime(2020, 7, 13, 15, 33, 48, 608, DateTimeKind.Local).AddTicks(3019),
                            FirstName = "john56",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 57,
                            Active = false,
                            CreatedAt = new DateTime(2020, 7, 15, 15, 33, 48, 608, DateTimeKind.Local).AddTicks(3022),
                            FirstName = "john57",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 58,
                            Active = false,
                            CreatedAt = new DateTime(2020, 7, 17, 15, 33, 48, 608, DateTimeKind.Local).AddTicks(3025),
                            FirstName = "john58",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 59,
                            Active = false,
                            CreatedAt = new DateTime(2020, 7, 19, 15, 33, 48, 608, DateTimeKind.Local).AddTicks(3028),
                            FirstName = "john59",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 60,
                            Active = false,
                            CreatedAt = new DateTime(2020, 7, 21, 15, 33, 48, 608, DateTimeKind.Local).AddTicks(3031),
                            FirstName = "john60",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 61,
                            Active = false,
                            CreatedAt = new DateTime(2020, 7, 23, 15, 33, 48, 608, DateTimeKind.Local).AddTicks(3037),
                            FirstName = "john61",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 62,
                            Active = false,
                            CreatedAt = new DateTime(2020, 7, 25, 15, 33, 48, 608, DateTimeKind.Local).AddTicks(3040),
                            FirstName = "john62",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 63,
                            Active = false,
                            CreatedAt = new DateTime(2020, 7, 27, 15, 33, 48, 608, DateTimeKind.Local).AddTicks(3043),
                            FirstName = "john63",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 64,
                            Active = false,
                            CreatedAt = new DateTime(2020, 7, 29, 15, 33, 48, 608, DateTimeKind.Local).AddTicks(3046),
                            FirstName = "john64",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 65,
                            Active = false,
                            CreatedAt = new DateTime(2020, 7, 31, 15, 33, 48, 608, DateTimeKind.Local).AddTicks(3049),
                            FirstName = "john65",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 66,
                            Active = false,
                            CreatedAt = new DateTime(2020, 8, 2, 15, 33, 48, 608, DateTimeKind.Local).AddTicks(3091),
                            FirstName = "john66",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 67,
                            Active = false,
                            CreatedAt = new DateTime(2020, 8, 4, 15, 33, 48, 608, DateTimeKind.Local).AddTicks(3094),
                            FirstName = "john67",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 68,
                            Active = false,
                            CreatedAt = new DateTime(2020, 8, 6, 15, 33, 48, 608, DateTimeKind.Local).AddTicks(3097),
                            FirstName = "john68",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 69,
                            Active = false,
                            CreatedAt = new DateTime(2020, 8, 8, 15, 33, 48, 608, DateTimeKind.Local).AddTicks(3103),
                            FirstName = "john69",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 70,
                            Active = false,
                            CreatedAt = new DateTime(2020, 8, 10, 15, 33, 48, 608, DateTimeKind.Local).AddTicks(3106),
                            FirstName = "john70",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 71,
                            Active = false,
                            CreatedAt = new DateTime(2020, 8, 12, 15, 33, 48, 608, DateTimeKind.Local).AddTicks(3109),
                            FirstName = "john71",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 72,
                            Active = false,
                            CreatedAt = new DateTime(2020, 8, 14, 15, 33, 48, 608, DateTimeKind.Local).AddTicks(3112),
                            FirstName = "john72",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 73,
                            Active = false,
                            CreatedAt = new DateTime(2020, 8, 16, 15, 33, 48, 608, DateTimeKind.Local).AddTicks(3115),
                            FirstName = "john73",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 74,
                            Active = false,
                            CreatedAt = new DateTime(2020, 8, 18, 15, 33, 48, 608, DateTimeKind.Local).AddTicks(3121),
                            FirstName = "john74",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 75,
                            Active = false,
                            CreatedAt = new DateTime(2020, 8, 20, 15, 33, 48, 608, DateTimeKind.Local).AddTicks(3124),
                            FirstName = "john75",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 76,
                            Active = false,
                            CreatedAt = new DateTime(2020, 8, 22, 15, 33, 48, 608, DateTimeKind.Local).AddTicks(3127),
                            FirstName = "john76",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 77,
                            Active = false,
                            CreatedAt = new DateTime(2020, 8, 24, 15, 33, 48, 608, DateTimeKind.Local).AddTicks(3130),
                            FirstName = "john77",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 78,
                            Active = false,
                            CreatedAt = new DateTime(2020, 8, 26, 15, 33, 48, 608, DateTimeKind.Local).AddTicks(3133),
                            FirstName = "john78",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 79,
                            Active = false,
                            CreatedAt = new DateTime(2020, 8, 28, 15, 33, 48, 608, DateTimeKind.Local).AddTicks(3139),
                            FirstName = "john79",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 80,
                            Active = false,
                            CreatedAt = new DateTime(2020, 8, 30, 15, 33, 48, 608, DateTimeKind.Local).AddTicks(3142),
                            FirstName = "john80",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 81,
                            Active = false,
                            CreatedAt = new DateTime(2020, 9, 1, 15, 33, 48, 608, DateTimeKind.Local).AddTicks(3145),
                            FirstName = "john81",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 82,
                            Active = false,
                            CreatedAt = new DateTime(2020, 9, 3, 15, 33, 48, 608, DateTimeKind.Local).AddTicks(3148),
                            FirstName = "john82",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 83,
                            Active = false,
                            CreatedAt = new DateTime(2020, 9, 5, 15, 33, 48, 608, DateTimeKind.Local).AddTicks(3151),
                            FirstName = "john83",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 84,
                            Active = false,
                            CreatedAt = new DateTime(2020, 9, 7, 15, 33, 48, 608, DateTimeKind.Local).AddTicks(3154),
                            FirstName = "john84",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 85,
                            Active = false,
                            CreatedAt = new DateTime(2020, 9, 9, 15, 33, 48, 608, DateTimeKind.Local).AddTicks(3160),
                            FirstName = "john85",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 86,
                            Active = false,
                            CreatedAt = new DateTime(2020, 9, 11, 15, 33, 48, 608, DateTimeKind.Local).AddTicks(3163),
                            FirstName = "john86",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 87,
                            Active = false,
                            CreatedAt = new DateTime(2020, 9, 13, 15, 33, 48, 608, DateTimeKind.Local).AddTicks(3166),
                            FirstName = "john87",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 88,
                            Active = false,
                            CreatedAt = new DateTime(2020, 9, 15, 15, 33, 48, 608, DateTimeKind.Local).AddTicks(3169),
                            FirstName = "john88",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 89,
                            Active = false,
                            CreatedAt = new DateTime(2020, 9, 17, 15, 33, 48, 608, DateTimeKind.Local).AddTicks(3172),
                            FirstName = "john89",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 90,
                            Active = false,
                            CreatedAt = new DateTime(2020, 9, 19, 15, 33, 48, 608, DateTimeKind.Local).AddTicks(3178),
                            FirstName = "john90",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 91,
                            Active = false,
                            CreatedAt = new DateTime(2020, 9, 21, 15, 33, 48, 608, DateTimeKind.Local).AddTicks(3181),
                            FirstName = "john91",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 92,
                            Active = false,
                            CreatedAt = new DateTime(2020, 9, 23, 15, 33, 48, 608, DateTimeKind.Local).AddTicks(3184),
                            FirstName = "john92",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 93,
                            Active = false,
                            CreatedAt = new DateTime(2020, 9, 25, 15, 33, 48, 608, DateTimeKind.Local).AddTicks(3187),
                            FirstName = "john93",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 94,
                            Active = false,
                            CreatedAt = new DateTime(2020, 9, 27, 15, 33, 48, 608, DateTimeKind.Local).AddTicks(3190),
                            FirstName = "john94",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 95,
                            Active = false,
                            CreatedAt = new DateTime(2020, 9, 29, 15, 33, 48, 608, DateTimeKind.Local).AddTicks(3194),
                            FirstName = "john95",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 96,
                            Active = false,
                            CreatedAt = new DateTime(2020, 10, 1, 15, 33, 48, 608, DateTimeKind.Local).AddTicks(3200),
                            FirstName = "john96",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 97,
                            Active = false,
                            CreatedAt = new DateTime(2020, 10, 3, 15, 33, 48, 608, DateTimeKind.Local).AddTicks(3203),
                            FirstName = "john97",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 98,
                            Active = false,
                            CreatedAt = new DateTime(2020, 10, 5, 15, 33, 48, 608, DateTimeKind.Local).AddTicks(3206),
                            FirstName = "john98",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        },
                        new
                        {
                            UserId = 99,
                            Active = false,
                            CreatedAt = new DateTime(2020, 10, 7, 15, 33, 48, 608, DateTimeKind.Local).AddTicks(3209),
                            FirstName = "john99",
                            LastName = "doe",
                            Username = "NameyNamey1"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
